### ISSUE TITLE
Unable to talk to server from JAMF Pro

### ISSUE THREAD

**Issue by CraigLindsey** [brysontyrrell/PatchServer#2]
I'm sure I've missed something simple but our test JPS doesn't seem able to talk to my test Patch server. JPS says "A connection error occurred while attempting to download software titles from this source."

I can talk to the PatchServer in a browser from the JPS box. I've checked the IP and port number and toggled SSL in the JPS patch server config. 

What am I missing?

**Comment by freddiep1983** [comment]
Same experience here.

Its all very new, so hopefully it is something we missed, however I can see an error in JAMF pro when I test the connection.

> OVERALLSTATUS
One or more external patch server tests failed.
SERVER STATUS
External patch server is running.
/SOFTWARE ENDPOINT VALIDATION
Attempt to connect to endpoint failed.


Equally on the Patch server instance, when run in verbose mode is actually showing the endpoint request for /software is throwing a 404 error.

`[13/Feb/2018 23:36:52] "GET /software HTTP/1.1" 404 `

**Also, should note; Thank you Bryson for all the hard work getting this ready for a day0 functionality drop ;)**

**Comment by brysontyrrell** [comment]
This is bad documentation on my part. I meant to update the Jamf Pro Setup instructions, and that slipped. I'll do that later tonight.

Refer to this screenshot for how to enter in the **SERVER** in Jamf Pro. You should have **/jamf/v1** at the end of the address.

![jamf_setup_02](https://user-images.githubusercontent.com/3086245/36180389-d765eb60-10e5-11e8-95c1-d3795bd64e7e.png)

If you can confirm this addresses it, I'll close the issue after I've pushed an update to the docs!

**Comment by freddiep1983** [comment]
@brysontyrrell 

Confirmed.
Works like a charm, now I have some definitions to make.

Thanks again man!
fred

**Comment by brysontyrrell** [comment]
Updated instructions committed: 8483a0a 

Docs were updated with the commit: http://patchserver.readthedocs.io/en/latest/setup/in_jamf_pro.html

**Comment by CraigLindsey** [comment]
Beautiful! I should have guessed that. 

I'll echo @freddiep1983 Thank you so much for all the work!
