### ISSUE TITLE
FR: Ability to update patch definitions in web UI

### ISSUE THREAD

**Issue by krispayne** [brysontyrrell/PatchServer#5]
"Not all of us are engineers, of course. Thus…"

Would be nice to be able to increment a Title's version somewhere in the web interface.

**Comment by brysontyrrell** [comment]
This was brought up by someone else in Slack (Emily I think). I'll add a button to the software title's row in the UI that will let you select a JSON file to upload to increment the version. It'll go through the same validation as using the full definition upload or API.

**Comment by krispayne** [comment]
Is there a channel for Patch Server on macadmins? Would love to participate in making this a better product!

**Comment by krispayne** [comment]
#patchserver in macadmins for those coming to this :-)

**Comment by brysontyrrell** [comment]
This has been implemented. See pull request #11
