### ISSUE TITLE
HTTP 404 returned with HEAD request

### ISSUE THREAD

**Issue by soja92** [brysontyrrell/PatchServer#8]
I am setting up a test environment for patching the software we use that isn't curated by Jamf and I ran into an issue when adding the patch server to JSS. When testing the external patch source it returns an error saying it cannot verify the /software endpoint.

I initially wanted to use apache as a reverse proxy in front of this API, but the error shows whether I use apache or not. 

This is the error with apache as a reverse proxy:
127.0.0.1 - - [03/Apr/2018 11:06:19] "HEAD /jamf/v1/ HTTP/1.1" 404 -
127.0.0.1 - - [03/Apr/2018 11:06:19] "GET /jamf/v1/software HTTP/1.1" 200 -

and without:
172.21.7.10 - - [03/Apr/2018 11:26:56] "HEAD /jamf/v1/ HTTP/1.1" 404 -
172.21.7.10 - - [03/Apr/2018 11:26:56] "GET /jamf/v1/software HTTP/1.1" 200 -

I have 1 software title added and the output of the /software endpoint is:
[
  {
    "currentVersion": "3.32.0-rc1", 
    "id": "FileZilla", 
    "lastModified": "2018-03-31T21:46:05Z", 
    "name": "FileZilla", 
    "publisher": ""
  }
]
This software title definition was made with the patch starter script.

If this software still works fine for Jamf Pro 10.2 for others, I can look into issues in my environment.

Thanks for looking!

**Comment by brysontyrrell** [comment]
@soja92 You can ignore those 404 errors.

For your definition, re-upload it to the server and make sure to include a value for the "publisher".

If you're using my Patch Starter Script, the publisher field is left blank if you don't supply a value for it in the arguments. This is an oversight, there needs to be a value there. I'll be making a quick update on that repo to set a default if one isn't provided.

**Comment by brysontyrrell** [comment]
@soja92 I've made that update to the script here:

https://github.com/brysontyrrell/Patch-Starter-Script/commit/9392241adfaf9a50da82916d185fa6945f6a2a36

**Comment by soja92** [comment]
I added a publisher and the JSS has no more errors

Thank you for creating these tools!
